No mock with frozen binaries
```
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 24, in <module>
  File "run_curator.py", line 5, in <module>
  File "/tmp/curator/curator-5.1.0/curator/__init__.py", line 5, in <module>
  File "/tmp/curator/curator-5.1.0/curator/utils.py", line 6, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/mock/__init__.py", line 2, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/mock/mock.py", line 71, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/pbr/version.py", line 461, in semantic_version
  File "/home/buh/.local/lib/python3.6/site-packages/pbr/version.py", line 438, in _get_version_from_pkg_resources
  File "/home/buh/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 70, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
ImportError: The 'appdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

Packages work without mock, so I went back to the old string comparison way for Mock, at least.

Bump version to 5.1.1